name: Download Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  get_asset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: List Releases
        run: gh release list --repo listendev/lstn
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}

      - name: Fetch asset
        run: gh release download --repo listendev/lstn 1.0
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}