name: Download Release

on: push

jobs:
  get_asset:
    runs-on: ubuntu-latest
    steps:
      - name: List Releases
        run: gh release list --repo listendev/lstn
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}